apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-service-account-binding
subjects:
  - kind: ServiceAccount
    name: traefik-service-account
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: traefik-cluster-role
  apiGroup: rbac.authorization.k8s.io