apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-cluster-role
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "secrets", "pods", "endpointslices", "nodes"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "ingressclasses"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["traefik.containo.us"]
    resources: [
      "ingressroutes", "middlewares", "tlsstores", "tlsoptions", "traefikservices", "serverstransports",
      "ingressrouteudps", "ingressroutetcps", "middlewaretcps"
    ]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["traefik.io"]
    resources: [
      "ingressroutes", "middlewares", "traefikservices", "serverstransports", "tlsstores", "tlsoptions",
      "middlewaretcps", "ingressrouteudps", "ingressroutetcps"
    ]
    verbs: ["get", "list", "watch", "create", "update", "delete"]

  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["traefik.containo.us"]
    resources: ["certificatesresolvers"]
    verbs: ["get", "list", "watch", "create"]