apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-cluster-role
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
  
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  
  - apiGroups: ["traefik.containo.us"]
    resources: [
      "ingressroutes", "middlewares", "tlsstores", "tlsoptions", "traefikservices", "serverstransports"
    ]
    verbs: ["get", "list", "watch"]
