package com.bellako.kiwi.analytics

object FirebaseEventNames {
    // Retention
    const val APP_OPENED = "APP_OPENED"
    const val PERMISSION_GRANTED = "PERMISSION_GRANTED"

    // SignUp
    const val SIGNUP_1_STARTED = "SIGNUP_1_STARTED"
    const val SIGNUP_2_FORM_INVALID_PASSWORD = "SIGNUP_2_FORM_INVALID_PASSWORD"
    const val SIGNUP_2_FORM_COMPLETED = "SIGNUP_2_FORM_COMPLETED"
    const val SIGNUP_3_TEST_COMPLETED = "SIGNUP_3_TEST_COMPLETED"
    const val SIGNUP_4_APPS_COMPLETED = "SIGNUP_4_APPS_COMPLETED"

    // Map
    const val MAP_PERFORM_ZOOM = "MAP_PERFORM_ZOOM"

    // Dashboard
    const val DASHBOARD_SEE_DAY = "DASHBOARD_SEE_DAY"

    // Settings
    const val SETTINGS_CLICK_ON_EMAIL = "SETTINGS_CLICK_ON_EMAIL"
    const val SETTINGS_UPDATE_VOLUME = "SETTINGS_UPDATE_VOLUME"
    const val SETTINGS_RESET_PROGRESS = "SETTINGS_RESET_PROGRESS"
}
