name: kiwi-prod
services:
  db:
    image: mysql:8
    container_name: kiwi-mysql-prod
    restart: always
    env_file:
      - ./.env.prod
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/mysql/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: kiwi-backend-prod
    depends_on:
      - db
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - BACKEND_DB_USERNAME=${BACKEND_DB_USERNAME}
      - BACKEND_DB_PASSWORD=${BACKEND_DB_PASSWORD}
    env_file:
      - ./backend/.env.prod
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: kiwi-frontend-prod
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.prod
    ports:
      - "80:80"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
