name: kiwi-dev
services:
  db:
    image: mysql:8
    container_name: kiwi-mysql-dev
    restart: always
    env_file:
      - ./.env.dev
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/mysql/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: kiwi-backend-dev
    depends_on:
      - db
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - BACKEND_DB_USERNAME=${BACKEND_DB_USERNAME}
      - BACKEND_DB_PASSWORD=${BACKEND_DB_PASSWORD}
    env_file:
      - ./backend/.env.dev
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: kiwi-frontend-dev
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.dev
    ports:
      - "5173:5173"
      - "9222:9222"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHROME_REMOTE_DEBUGGING_PORT=9222
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
