apiVersion: v1
kind: Service
metadata:
  name: kiwi-mysql-prod-service
  namespace: prod 
spec:
  type: NodePort
  selector:
    app: kiwi-mysql-prod
  ports:
    - protocol: TCP
      port: 3306 
      targetPort: 3306
      nodePort: 30307
# spec:
#   type: ClusterIP 
#   selector:
#     app: kiwi-mysql-prod
#   ports:
#     - protocol: TCP
#       port: 3306
#       targetPort: 3306
