apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kiwi-ci-cd-cluster-role
rules:
  - apiGroups: ["", "apps", "networking.k8s.io"]
    resources: ["deployments", "services", "ingresses"]
    verbs: ["get", "list", "create", "patch"]
