apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kiwi-ci-cd-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: kiwi-ci-cd-service-account
    namespace: prod
roleRef:
  kind: ClusterRole
  name: kiwi-ci-cd-cluster-role
  apiGroup: rbac.authorization.k8s.io
