apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiwi-mysql-prod-pvc
  namespace: prod
  labels:
    app: kiwi-mysql-prod
    tier: database
    environment: prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi 
  storageClassName: local-path
