apiVersion: v1
kind: Service
metadata:
  name: kiwi-frontend-prod-service
  namespace: prod
  labels:
    app: kiwi-frontend-prod
    tier: frontend
    environment: prod
spec:
  selector:
    app: kiwi-frontend-prod
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 80
  type: ClusterIP     
