apiVersion: v1
kind: Service
metadata:
  name: kiwi-backend-prod-service
  namespace: prod
  labels:
    app: kiwi-backend-prod
    tier: backend
    environment: prod
spec:
  selector:
    app: kiwi-backend-prod
  ports:
    - protocol: TCP
      port: 80     
      targetPort: 8080
  type: ClusterIP
