CREATE TABLE incidences (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS user_incidences (
    user_id BIGINT NOT NULL,
    incidence_id BIGINT NOT NULL,
    value BOOLEAN NOT NULL DEFAULT FALSE
);