ALTER TABLE combat_log
    MODIFY COLUMN target ENUM('USER','ENEMY','ALLY') NULL;

ALTER TABLE combat_log
    MODIFY COLUMN actor ENUM('USER','ENEMY','ALLY') NOT NULL;

ALTER TABLE combat_log
    MODIFY COLUMN action_type ENUM(
        'SKILL_USED',
        'ACTOR_BLOCKED_BY_STATE',
        'SKILL_REPEAT_BY_STATE',
        'ACTOR_DAMAGED_BY_STATE',
        'BLOCKED_SKILLS_BY_STATE',
        'RELEASED_SKILLS_BY_STATE',
        'SKIP',
        'STATUS_TURN_REDUCED',
        'STATUS_FINISHED',
        'TIMEOUT',
        'ABANDON'
    ) NOT NULL;