-- Seed data for the `goals` table.
-- Generated from the Goals knowledge base export.
-- Notes on transformations applied:
--   * Rows with a non-integer `target` (e.g. ranges/text) were excluded (13 rows).
--   * `type` values were normalized to GoalType constants (UPPER, spaces/hyphens -> underscores).
--   * `category` is set to DAILY_CHALLENGES for every row.
--   * Empty `reward` defaulted to 1; empty `on_completed_entity` -> '' and `on_completed_entity_id` -> 0.
--   * IDs: duplicates kept first occurrence; duplicate-extras and empty IDs were assigned
--     fresh sequential IDs starting at 7303 (5 reassigned, 316 filled).
-- Ignored source columns: conversation to start(/id), scalable?, skills_to_gain(/id), slider?, usage.

ALTER TABLE goals MODIFY COLUMN type     VARCHAR(64) NOT NULL;
ALTER TABLE goals MODIFY COLUMN category VARCHAR(64) NOT NULL;

INSERT INTO goals
    (id, name, action, target, type, category, reward, difficulty, on_completed_action, on_completed_entity, on_completed_entity_id)
VALUES
    (1001, 'Complete Pomodoro sessions', 'Complete Pomodoro sessions', 4, 'FOCUS', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 2080),
    (1004, 'Set a clear stop condition before starting a task', 'Set a clear stop condition before starting a task', 1, 'FOCUS', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1101, 'Start a postponed task', 'Start a postponed task', 1, 'PROCRASTINATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1102, 'Break tasks into 3 steps', 'Break any task into 3 steps', 5, 'PROCRASTINATION', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 6070),
    (1103, 'Remove distractions', 'Remove distractions', 5, 'PROCRASTINATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1104, 'Finish one small pending task', 'Finish one small pending task', 1, 'PROCRASTINATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1105, 'Replace “later” with a specific time', 'Replace “later” with a specific time', 1, 'PROCRASTINATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1202, 'Clean your workspace', 'Clean your workspace', 3, 'CLARITY', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1205, 'Drink water before start working', 'Drink water before start working', 10, 'CLARITY', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 3020),
    (1301, 'Set a clear stop time', 'Set a clear stop time', 1, 'WORK_LIFE_BALANCE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1302, 'Close all work apps after work', 'Close all work apps after work', 1, 'WORK_LIFE_BALANCE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1304, 'Do one guilt-free activity', 'Do one guilt-free activity', 1, 'WORK_LIFE_BALANCE', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 4080),
    (1305, 'Leave your work area and change clothes when done', 'Leave your work area and change clothes when done', 1, 'WORK_LIFE_BALANCE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1402, 'Stretch your body', 'Stretch your body', 10, 'RECOVERY', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 5040),
    (1502, 'Remove one app shortcut', 'Remove one app shortcut', 1, 'TECH_BALANCE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1503, 'Unlock your phone with intention', 'Unlock your phone with intention', 10, 'TECH_BALANCE', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 2040),
    (1601, 'Rate today’s focus level', 'Rate today’s focus level', 1, 'REFLECTION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1602, 'Note one resisted distraction', 'Note one resisted distraction', 1, 'REFLECTION', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 5030),
    (1603, 'Write one energy drain', 'Write one energy drain', 1, 'REFLECTION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1604, 'Identify one focus boost', 'Identify one focus boost', 1, 'REFLECTION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1605, 'Set tomorrow’s main task', 'Set tomorrow’s main task', 1, 'REFLECTION', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 5070),
    (1701, 'Do one task slowly', 'Do one task slowly', 1, 'PRESENCE', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 5060),
    (7001, 'Focus on your breath for 10 minutes', 'Focus on your breath for 10 minutes', 3, 'MEDITATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7101, 'Text your loved ones', 'Text your loved ones', 3, 'CARING', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 4010),
    (1106, 'Do the hardest task first', 'Do the hardest task first', 3, 'PROCRASTINATION', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 2060),
    (1107, 'Start before feeling ready', 'Start before feeling ready', 5, 'PROCRASTINATION', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 2070),
    (1108, 'Finish at 80% done', 'Finish at 80% done', 5, 'PROCRASTINATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1005, 'Work with a visible timer', 'Work with a visible timer', 1, 'FOCUS', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1006, 'Re-focus after distraction', 'Re-focus after distraction', 10, 'FOCUS', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 5020),
    (1007, 'Reduce task scope on purpose', NULL, 5, 'FOCUS', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 6060),
    (1206, 'Empty your inbox', 'Empty your inbox', 1, 'CLARITY', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1207, 'Remove clutter from your desk', 'Remove clutter from your desk', 1, 'CLARITY', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1306, 'Leave work unfinished on purpose', 'Leave work unfinished on purpose', 3, 'WORK_LIFE_BALANCE', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 2020),
    (1405, 'Drink water before coffee', 'Drink water before every coffee cup', 1, 'RECOVERY', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1507, 'Disable one notification', 'Disable one notification permanently', 1, 'TECH_BALANCE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1508, 'Close apps after each use', 'Close apps after each use', 20, 'TECH_BALANCE', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 6040),
    (1308, 'End work with a closing ritual', 'End work with a closing ritual', 1, 'WORK_LIFE_BALANCE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1309, 'Stop one task earlier than usual', 'Stop one task earlier than usual', 1, 'WORK_LIFE_BALANCE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1008, 'Finish a task without reopening it', NULL, 1, 'FOCUS', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1109, 'Skip optimization for one task', 'Skip optimization for one task', 5, 'PROCRASTINATION', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 5050),
    (1406, 'Rest without stimulation', 'Rest 10 minutes without stimulation', 5, 'RECOVERY', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 3080),
    (1408, 'Take a break before feeling tired', 'Take a break before feeling tired', 1, 'RECOVERY', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1310, 'Do not discuss work after hours', 'Do not discuss work after hours', 1, 'WORK_LIFE_BALANCE', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 4020),
    (1208, 'Switch tasks when energy drops', 'Switch tasks when energy drops', 5, 'CLARITY', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 5010),
    (1509, 'Do not refresh feeds', 'Do not refresh feeds', 10, 'TECH_BALANCE', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 6020),
    (1510, 'Consume only one content source', 'Consume only one content source', 1, 'TECH_BALANCE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7106, 'Send a meme to a friend and tell them it reminded you of them', 'Send a meme to a friend and tell them it reminded you of them', 1, 'CARING', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7105, 'Call your mom/dad on a random hour', 'Call your mom/dad on a random hour', 1, 'CARING', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7104, 'Send a random emoji to someone you haven’t talked in a time', 'Send a random emoji to someone you haven’t talked in a time', 1, 'CARING', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7103, 'Plan an activity with someone you like for this week', 'Plan an activity with someone you like for this week', 1, 'CARING', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7102, 'Call a friend', 'Call a friend', 3, 'CARING', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 4040),
    (7303, 'Create a top-10 priority list for your week', 'Create a top-10 priority list for your week', 1, 'CLARITY', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7304, 'Do the wheel-of-life exercise', 'Do the wheel-of-life exercise', 1, 'CLARITY', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (4604, 'Do burpees', 'Do burpees', 20, 'REGULATION', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 1070),
    (4603, 'Do sit-ups', 'Do sit-ups', 30, 'REGULATION', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 1060),
    (4301, 'Brush your teeth', 'Brush your teeth', 3, 'BODY_CARE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (4407, 'Stretch before going to bed', 'Stretch before going to bed', 1, 'REHAB', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1012, 'Create a “to-do-later note” and write down all distractions there', 'Create a “to-do-later note” and write down all distractions there', 1, 'FOCUS', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1011, 'Reduce your number of active tasks to 3 or less', 'Reduce your number of active tasks to 3 or less', 1, 'FOCUS', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7007, 'Pay attention to the otters you percieve during showering', 'Pay attention to the otters you percieve during showering', 1, 'MEDITATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7305, 'Go to a fun coffee shop to complete your tasks', 'Go to a coffee shop or library to complete your tasks', 1, 'PROCRASTINATION', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 4030),
    (1112, 'Play Pokémon OST while you work', 'Play Pokémon OST while you work', 1, 'PROCRASTINATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1111, 'Work for just 5 minutes. If you feel like it, you can quit afterwards', 'Work for just 5 minutes. If you feel like it, you can quit afterwards', 1, 'PROCRASTINATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1110, 'Stop and think about your task step-by-step plan before you start', 'Stop and think about your task step-by-step plan before you start', 1, 'PROCRASTINATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (4009, 'Reach to your max effort in a workout', 'Reach to your max effort in a workout', 1, 'EXERCISE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7301, 'Set an intention for the day', 'Set an intention for the day', 1, 'INTENTION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (4108, 'Eat mainly protein in every main meal', 'Eat mainly protein in every main meal', 1, 'NUTRITION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7306, 'Wait some time before taking a second serving', 'Wait 10 minutes before taking a second serving', 3, 'NUTRITION', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 3050),
    (4202, 'Go to bed within a fixed window', 'Go to bed at your desired, fixed time', 1, 'REST', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (4203, 'Wake up without snooze', 'Wake up without snooze', 1, 'REST', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (4206, 'Wake up at the same time for several days in a row', 'Wake up at the same time than yesterday', 5, 'REST', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (4401, 'Take a full rest or power nap', 'Take a full rest or power nap', 5, 'REHAB', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 3030),
    (4302, 'Check and correct posture', 'Check and correct posture', 10, 'BODY_CARE', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 3000),
    (4402, 'Do breathing exercises', 'Do 5 minutes of breathing exercises', 5, 'REHAB', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (4403, 'Do light stretching', 'Do some light stretching', 5, 'REHAB', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7209, 'Notice emotional shifts during the day', 'Notice emotional shifts during the day', 1, 'AWARENESS', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (4406, 'Slow your breathing', 'Slow your breathing', 10, 'REHAB', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7208, 'Cry, breath or move to release emotional tension', 'Cry, breath or move to release emotional tension', 1, 'AWARENESS', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7207, 'Let yourself feel without fixing', 'Let yourself feel without fixing', 1, 'AWARENESS', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7206, 'Name your current emotion', 'Name your current emotion', 5, 'AWARENESS', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 6010),
    (7202, 'Write what you feel right now', 'Write what you feel right now', 1, 'AWARENESS', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7203, 'Accept a negative emotion without resisting', 'Accept a negative emotion without resisting', 1, 'AWARENESS', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7204, 'Identify what triggered your current emotion', 'Identify what triggered your current emotion', 5, 'AWARENESS', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 6080),
    (7201, 'Express your feelings honestly', 'Express your feelings honestly', 3, 'AWARENESS', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 4060),
    (7205, 'Sit with discomfort without distraction', 'Sit with discomfort without distraction during 10 minutes', 1, 'AWARENESS', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7109, 'Prepare a little surprise for someone’s birthday', 'Prepare a little surprise for someone’s birthday', 1, 'CARING', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (4609, 'Take a short movement break', 'Take a short movement break', 5, 'REGULATION', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 1010),
    (7108, 'Ask someone how they are and listen', 'Ask someone how they are and listen', 3, 'CARING', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 4000),
    (7107, 'Reply to pending messages', 'Reply to pending messages', 10, 'CARING', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (4610, 'Cool down your body with cold water or fresh air\n', 'Cool down your body with cold water or fresh air\n', 5, 'REGULATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7302, 'Reconnect with a personal value', 'Reconnect with a personal value', 1, 'INTENTION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1114, 'Play Minecraft OST while you work', 'Play Minecraft OST while you work', 1, 'PROCRASTINATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (1113, 'Play The Legend of Zelda OST while you work', 'Play The Legend of Zelda OST while you work', 1, 'PROCRASTINATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7307, 'Play lo-fi ambient music while you work', 'Play lo-fi ambient music while you work', 1, 'PROCRASTINATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (4011, 'Take a short walk outside your usual routine', 'Take a short walk outside your usual routine', 3, 'EXERCISE', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 1020),
    (4012, 'Complete your usual workout routine', 'Complete your usual workout routine', 1, 'EXERCISE', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 1000),
    (4605, 'Do jumping jacks', 'Do jumping jacks', 50, 'REGULATION', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 1050),
    (4606, 'Do high knees', 'Do high knees', 50, 'REGULATION', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 1040),
    (4607, 'Do planks', 'Do planks', 3, 'REGULATION', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 1080),
    (4611, 'Do lunges', 'Do lunges', 40, 'REGULATION', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 1030),
    (7308, 'Observe the void inside your solar plaxes', 'Observe the void inside your solar plaxes during @VARIABLE minutes', 3, 'MEDITATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7309, 'Run at a steady pace', 'Run @VARIABLE minutes at a steady pace', 25, 'EXERCISE', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7310, 'Put your phone out of reach', 'Put your phone out of reach during @VARIABLE minutes', 60, 'TECH_BALANCE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7311, 'Avoid work messages (streak)', 'Avoid work messages during @VARIABLE hours', 8, 'WORK_LIFE_BALANCE', 'DAILY_CHALLENGES', 1, 3, 'GAIN', 'SKILL', 0),
    (7312, 'Release muscle tension', 'Release muscle tension during @VARIABLE minutes', 20, 'REHAB', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7313, 'Read something other than social media', 'Read something other than social media during @VARIABLE hours', 30, 'TECH_BALANCE', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7314, 'Avoid screens for some time before sleep', 'Avoid screens for @VARIABLE minutes before sleep', 60, 'REST', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7315, 'Try to identify the nosal nostril that inhales more air', 'Try to identify the nosal nostril that inhales more air during @VARIABLE minutes', 10, 'MEDITATION', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7316, 'Lie down without stimulation', 'Lie down without stimulation during @VARIABLE minutes', 4, 'REHAB', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7317, 'Try to identify the nosal nostril that inhales more air', 'Try to identify the nosal nostril that inhales more air during @VARIABLE minutes', 4, 'MEDITATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7318, 'Release muscle tension', 'Release muscle tension during @VARIABLE minutes', 4, 'REHAB', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7319, 'Try to identify the nosal nostril that inhales more air', 'Try to identify the nosal nostril that inhales more air during @VARIABLE minutes', 6, 'MEDITATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7320, 'Picture air entering your foot and travelling to your head when you breath', 'Picture air entering your foot and travelling to your head when you breath during @VARIABLE minutes', 8, 'MEDITATION', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7321, 'Delay phone use after waking', 'Delay phone use @VARIABLE minutes after waking', 5, 'TECH_BALANCE', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7322, 'Release muscle tension', 'Release muscle tension during @VARIABLE minutes', 8, 'REHAB', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7323, 'Observe the void inside your solar plaxes', 'Observe the void inside your solar plaxes during @VARIABLE minutes', 1, 'MEDITATION', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7324, 'Release muscle tension', 'Release muscle tension during @VARIABLE minutes', 2, 'REHAB', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7325, 'Delay phone use after waking', 'Delay phone use @VARIABLE minutes after waking', 20, 'TECH_BALANCE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7326, 'Put your phone out of reach', 'Put your phone out of reach during @VARIABLE minutes', 90, 'TECH_BALANCE', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7327, 'Spend time on personal body care', 'Spend @VARIABLE minutes on personal body care', 15, 'BODY_CARE', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7328, 'Wait X minutes before your first coffee', 'Wait @VARIABLE minutes before your first coffee', 20, 'RECOVERY', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7329, 'Wait X minutes before your first coffee', 'Wait @VARIABLE minutes before your first coffee', 40, 'RECOVERY', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7330, 'Look at a distant point', 'Look at a distant point during @VARIABLE minutes', 4, 'RECOVERY', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7331, 'Get natural light', 'Get natural light during @VARIABLE minutes', 20, 'RECOVERY', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7332, 'Observe the void inside your solar plaxes', 'Observe the void inside your solar plaxes during @VARIABLE minutes', 4, 'MEDITATION', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7333, 'Avoid screens for some time before sleep', 'Avoid screens for @VARIABLE minutes before sleep', 90, 'REST', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7334, 'Spend time on personal body care', 'Spend @VARIABLE minutes on personal body care', 10, 'BODY_CARE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7335, 'Spend time on personal body care', 'Spend @VARIABLE minutes on personal body care', 20, 'BODY_CARE', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7336, 'Try to identify the nosal nostril that inhales more air', 'Try to identify the nosal nostril that inhales more air during @VARIABLE minutes', 2, 'MEDITATION', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7337, 'Look at a distant point', 'Look at a distant point during @VARIABLE minutes', 10, 'RECOVERY', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7338, 'Run at a steady pace', 'Run @VARIABLE minutes at a steady pace', 30, 'EXERCISE', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7339, 'Read something other than social media', 'Read something other than social media during @VARIABLE hours', 45, 'TECH_BALANCE', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7340, 'Workout for some time', 'Workout for at least @VARIABLE minutes', 60, 'EXERCISE', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7341, 'Get natural light', 'Get natural light during @VARIABLE minutes', 30, 'RECOVERY', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7342, 'Delay phone use after waking', 'Delay phone use @VARIABLE minutes after waking', 10, 'TECH_BALANCE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7343, 'Run at a steady pace', 'Run @VARIABLE minutes at a steady pace', 15, 'EXERCISE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7344, 'Put your phone out of reach', 'Put your phone out of reach during @VARIABLE minutes', 10, 'TECH_BALANCE', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7345, 'Put your phone out of reach', 'Put your phone out of reach during @VARIABLE minutes', 120, 'TECH_BALANCE', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7346, 'Lie down without stimulation', 'Lie down without stimulation during @VARIABLE minutes', 8, 'REHAB', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7347, 'Picture air entering your foot and travelling to your head when you breath', 'Picture air entering your foot and travelling to your head when you breath during @VARIABLE minutes', 2, 'MEDITATION', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7348, 'Read something other than social media', 'Read something other than social media during @VARIABLE hours', 20, 'TECH_BALANCE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7349, 'Lie down without stimulation', 'Lie down without stimulation during @VARIABLE minutes', 12, 'REHAB', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7350, 'Release muscle tension', 'Release muscle tension during @VARIABLE minutes', 12, 'REHAB', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7351, 'Run at a steady pace', 'Run @VARIABLE minutes at a steady pace', 10, 'EXERCISE', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7352, 'Get natural light', 'Get natural light during @VARIABLE minutes', 50, 'RECOVERY', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7353, 'Spend time on personal body care', 'Spend @VARIABLE minutes on personal body care', 7, 'BODY_CARE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7354, 'Focus on a single task', 'Focus on a single task during @VARIABLE minutes', 30, 'FOCUS', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7355, 'Wait X minutes before your first coffee', 'Wait @VARIABLE minutes before your first coffee', 10, 'RECOVERY', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7356, 'Avoid work messages (streak)', 'Avoid work messages during @VARIABLE hours', 6, 'WORK_LIFE_BALANCE', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 0),
    (7357, 'Lie down without stimulation', 'Lie down without stimulation during @VARIABLE minutes', 2, 'REHAB', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7358, 'Avoid work messages (streak)', 'Avoid work messages during @VARIABLE hours', 4, 'WORK_LIFE_BALANCE', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 0),
    (7359, 'Focus on a single task', 'Focus on a single task during @VARIABLE minutes', 10, 'FOCUS', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7360, 'Give awareness to the warm inside your body', 'Give awareness to the warm inside your body during @VARIABLE minutes', 3, 'MEDITATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7361, 'Avoid screens for some time before sleep', 'Avoid screens for @VARIABLE minutes before sleep', 45, 'REST', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7362, 'Try to identify the nosal nostril that inhales more air', 'Try to identify the nosal nostril that inhales more air during @VARIABLE minutes', 8, 'MEDITATION', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7363, 'Workout for some time', 'Workout for at least @VARIABLE minutes', 90, 'EXERCISE', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7364, 'Get natural light', 'Get natural light during @VARIABLE minutes', 40, 'RECOVERY', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7365, 'Run at a steady pace', 'Run @VARIABLE minutes at a steady pace', 20, 'EXERCISE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7366, 'Give awareness to the warm inside your body', 'Give awareness to the warm inside your body during @VARIABLE minutes', 5, 'MEDITATION', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7367, 'Picture air entering your foot and travelling to your head when you breath', 'Picture air entering your foot and travelling to your head when you breath during @VARIABLE minutes', 4, 'MEDITATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7368, 'Avoid screens for some time before sleep', 'Avoid screens for @VARIABLE minutes before sleep', 30, 'REST', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7369, 'Read something other than social media', 'Read something other than social media during @VARIABLE hours', 5, 'TECH_BALANCE', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7370, 'Observe the void inside your solar plaxes', 'Observe the void inside your solar plaxes during @VARIABLE minutes', 2, 'MEDITATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7371, 'Workout for some time', 'Workout for at least @VARIABLE minutes', 30, 'EXERCISE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7372, 'Give awareness to the warm inside your body', 'Give awareness to the warm inside your body during @VARIABLE minutes', 2, 'MEDITATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7373, 'Workout for some time', 'Workout for at least @VARIABLE minutes', 45, 'EXERCISE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7374, 'Get natural light', 'Get natural light during @VARIABLE minutes', 10, 'RECOVERY', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7375, 'Wait X minutes before your first coffee', 'Wait @VARIABLE minutes before your first coffee', 60, 'RECOVERY', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7376, 'Avoid work messages (streak)', 'Avoid work messages during @VARIABLE hours', 12, 'WORK_LIFE_BALANCE', 'DAILY_CHALLENGES', 1, 4, 'GAIN', 'SKILL', 6050),
    (7377, 'Give awareness to the warm inside your body', 'Give awareness to the warm inside your body during @VARIABLE minutes', 4, 'MEDITATION', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7378, 'Delay phone use after waking', 'Delay phone use @VARIABLE minutes after waking', 60, 'TECH_BALANCE', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7379, 'Delay phone use after waking', 'Delay phone use @VARIABLE minutes after waking', 40, 'TECH_BALANCE', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7380, 'Look at a distant point', 'Look at a distant point during @VARIABLE minutes', 2, 'RECOVERY', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7381, 'Read something other than social media', 'Read something other than social media during @VARIABLE hours', 10, 'TECH_BALANCE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7382, 'Picture air entering your foot and travelling to your head when you breath', 'Picture air entering your foot and travelling to your head when you breath during @VARIABLE minutes', 10, 'MEDITATION', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7383, 'Lie down without stimulation', 'Lie down without stimulation during @VARIABLE minutes', 20, 'REHAB', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7384, 'Avoid screens for some time before sleep', 'Avoid screens for @VARIABLE minutes before sleep', 75, 'REST', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7385, 'Picture air entering your foot and travelling to your head when you breath', 'Picture air entering your foot and travelling to your head when you breath during @VARIABLE minutes', 6, 'MEDITATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7386, 'Look at a distant point', 'Look at a distant point during @VARIABLE minutes', 6, 'RECOVERY', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7387, 'Give awareness to the warm inside your body', 'Give awareness to the warm inside your body during @VARIABLE minutes', 1, 'MEDITATION', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7388, 'Workout for some time', 'Workout for at least @VARIABLE minutes', 15, 'EXERCISE', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7389, 'Focus on a single task', 'Focus on a single task during @VARIABLE minutes', 60, 'FOCUS', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7390, 'Avoid work messages (streak)', 'Avoid work messages during @VARIABLE hours', 2, 'WORK_LIFE_BALANCE', 'DAILY_CHALLENGES', 1, 1, 'GAIN', 'SKILL', 0),
    (7391, 'Observe the void inside your solar plaxes', 'Observe the void inside your solar plaxes during @VARIABLE minutes', 5, 'MEDITATION', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7392, 'Focus on a single task', 'Focus on a single task during @VARIABLE minutes', 20, 'FOCUS', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7393, 'Focus on a single task', 'Focus on a single task during @VARIABLE minutes', 45, 'FOCUS', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7394, 'Wait X minutes before your first coffee', 'Wait @VARIABLE minutes before your first coffee', 90, 'RECOVERY', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7395, 'Look at a distant point', 'Look at a distant point during @VARIABLE minutes', 8, 'RECOVERY', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7396, 'Put your phone out of reach', 'Put your phone out of reach during @VARIABLE minutes', 30, 'TECH_BALANCE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7397, 'Spend time on personal body care', 'Spend @VARIABLE minutes on personal body care', 5, 'BODY_CARE', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7398, 'Avoid caffeine before sleep', 'Avoid caffeine @VARIABLE hours before sleep', 10, 'REST', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7399, 'Eat fruit', 'Eat @VARIABLE fruits', 5, 'NUTRITION', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7400, 'Avoid energy drinks', 'Avoid energy drinks during @VARIABLE hours', 48, 'REGULATION', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7401, 'Expose your eyes to natural light', 'Expose your eyes to natural light during @VARIABLE minutes', 30, 'NATURAL_EXPOSURE', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7402, 'Do mobility work', 'Do mobility work during @VARIABLE minutes', 25, 'EXERCISE', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7403, 'Avoid energy drinks', 'Avoid energy drinks during @VARIABLE hours', 24, 'REGULATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7404, 'Avoid caffeine for the first minutes after waking', 'Avoid caffeine for @VARIABLE minutes after waking', 60, 'REGULATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7405, 'Avoid energy drinks', 'Avoid energy drinks during @VARIABLE hours', 12, 'REGULATION', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7406, 'Avoid caffeine before sleep', 'Avoid caffeine @VARIABLE hours before sleep', 4, 'REST', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7407, 'Eat fruit', 'Eat @VARIABLE fruits', 2, 'NUTRITION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7408, 'Avoid ultra-processed food', 'Avoid ultra-processed food during @VARIABLE hours', 24, 'NUTRITION', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7409, 'Get sunlight after waking', 'Get sunlight during @VARIABLE minutes after waking', 60, 'NATURAL_EXPOSURE', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7410, 'Avoid sugar', 'Avoid sugar during @VARIABLE hours', 6, 'NUTRITION', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7411, 'Get sunlight after waking', 'Get sunlight during @VARIABLE minutes after waking', 30, 'NATURAL_EXPOSURE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7412, 'Get sunlight after waking', 'Get sunlight during @VARIABLE minutes after waking', 45, 'NATURAL_EXPOSURE', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7413, 'Eat without screens', 'Eat without screens in @VARIABLE meals', 4, 'NUTRITION', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7414, 'Hold a plank', 'Hold a @VARIABLE-second plank', 20, 'EXERCISE', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7415, 'Avoid screens before sleep', 'Avoid screens before sleep', 40, 'RECOVERY', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7416, 'Get sunlight after waking', 'Get sunlight during @VARIABLE minutes after waking', 10, 'NATURAL_EXPOSURE', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7417, 'Walk steps', 'Walk @VARIABLE steps', 15000, 'EXERCISE', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7418, 'Eat some vegetables', 'Eat @VARIABLE g of vegetables', 300, 'NUTRITION', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7419, 'Avoid caffeine before sleep', 'Avoid caffeine @VARIABLE hours before sleep', 8, 'REST', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7420, 'Hold a plank', 'Hold a @VARIABLE-second plank', 30, 'EXERCISE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7421, 'Eat fruit', 'Eat @VARIABLE fruits', 4, 'NUTRITION', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7422, 'Do several reps of a single exercise', 'Do @VARIABLE reps of a single exercise', 75, 'EXERCISE', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7423, 'Train with heavy weights', 'Train with heavy weights during @VARIABLE minutes', 15, 'EXERCISE', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7424, 'Prepare homemade meals', 'Prepare @VARIABLE homemade meals', 4, 'NUTRITION', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7425, 'Avoid sugar', 'Avoid sugar during @VARIABLE hours', 18, 'NUTRITION', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7426, 'Eat without screens', 'Eat without screens in @VARIABLE meals', 1, 'NUTRITION', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7427, 'Walk steps', 'Walk @VARIABLE steps', 12000, 'EXERCISE', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7428, 'Do several reps of a single exercise', 'Do @VARIABLE reps of a single exercise', 10, 'EXERCISE', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7429, 'Expose your eyes to natural light', 'Expose your eyes to natural light during @VARIABLE minutes', 15, 'NATURAL_EXPOSURE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7430, 'Do mobility work', 'Do mobility work during @VARIABLE minutes', 10, 'EXERCISE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7431, 'Avoid ultra-processed food', 'Avoid ultra-processed food during @VARIABLE hours', 8, 'NUTRITION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7432, 'Train with heavy weights', 'Train with heavy weights during @VARIABLE minutes', 45, 'EXERCISE', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7433, 'Avoid sugar', 'Avoid sugar during @VARIABLE hours', 24, 'NUTRITION', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7434, 'Walk steps', 'Walk @VARIABLE steps', 6000, 'EXERCISE', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7435, 'Avoid screens before sleep', 'Avoid screens before sleep', 10, 'RECOVERY', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7436, 'Train with heavy weights', 'Train with heavy weights during @VARIABLE minutes', 35, 'EXERCISE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7437, 'Eat fruit', 'Eat @VARIABLE fruits', 3, 'NUTRITION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7438, 'Train with heavy weights', 'Train with heavy weights during @VARIABLE minutes', 60, 'EXERCISE', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7439, 'Do several reps of a single exercise', 'Do @VARIABLE reps of a single exercise', 100, 'EXERCISE', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7440, 'Train with heavy weights', 'Train with heavy weights during @VARIABLE minutes', 25, 'EXERCISE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7441, 'Prepare homemade meals', 'Prepare @VARIABLE homemade meals', 2, 'NUTRITION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7442, 'Do mobility work', 'Do mobility work during @VARIABLE minutes', 15, 'EXERCISE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7443, 'Hold a plank', 'Hold a @VARIABLE-second plank', 60, 'EXERCISE', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7444, 'Eat fruit', 'Eat @VARIABLE fruits', 1, 'NUTRITION', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7445, 'Eat some vegetables', 'Eat @VARIABLE g of vegetables', 200, 'NUTRITION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7446, 'Eat some vegetables', 'Eat @VARIABLE g of vegetables', 150, 'NUTRITION', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7447, 'Eat without screens', 'Eat without screens in @VARIABLE meals', 5, 'NUTRITION', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7448, 'Avoid energy drinks', 'Avoid energy drinks during @VARIABLE hours', 72, 'REGULATION', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7449, 'Eat without screens', 'Eat without screens in @VARIABLE meals', 3, 'NUTRITION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7450, 'Do several reps of a single exercise', 'Do @VARIABLE reps of a single exercise', 50, 'EXERCISE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7451, 'Get sunlight after waking', 'Get sunlight during @VARIABLE minutes after waking', 20, 'NATURAL_EXPOSURE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7452, 'Avoid screens before sleep', 'Avoid screens before sleep', 30, 'RECOVERY', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7453, 'Avoid caffeine before sleep', 'Avoid caffeine @VARIABLE hours before sleep', 6, 'REST', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7454, 'Avoid energy drinks', 'Avoid energy drinks during @VARIABLE hours', 18, 'REGULATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7455, 'Prepare homemade meals', 'Prepare @VARIABLE homemade meals', 3, 'NUTRITION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7456, 'Avoid ultra-processed food', 'Avoid ultra-processed food during @VARIABLE hours', 2, 'NUTRITION', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7457, 'Avoid sugar', 'Avoid sugar during @VARIABLE hours', 9, 'NUTRITION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7458, 'Sleep a reasonable amount of time', 'Sleep @VARIABLE hours', 7, 'REST', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7459, 'Eat some vegetables', 'Eat @VARIABLE g of vegetables', 250, 'NUTRITION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7460, 'Walk in a natural environment', 'Walk in a natural environment during @VARIABLE minutes', 45, 'NATURAL_EXPOSURE', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7461, 'Walk in a natural environment', 'Walk in a natural environment during @VARIABLE minutes', 20, 'NATURAL_EXPOSURE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7462, 'Expose your eyes to natural light', 'Expose your eyes to natural light during @VARIABLE minutes', 20, 'NATURAL_EXPOSURE', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7463, 'Hold a plank', 'Hold a @VARIABLE-second plank', 90, 'EXERCISE', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7464, 'Avoid caffeine for the first minutes after waking', 'Avoid caffeine for @VARIABLE minutes after waking', 30, 'REGULATION', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7465, 'Avoid screens before sleep', 'Avoid screens before sleep', 20, 'RECOVERY', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7466, 'Expose your eyes to natural light', 'Expose your eyes to natural light during @VARIABLE minutes', 5, 'NATURAL_EXPOSURE', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7467, 'Do mobility work', 'Do mobility work during @VARIABLE minutes', 20, 'EXERCISE', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7468, 'Walk in a natural environment', 'Walk in a natural environment during @VARIABLE minutes', 30, 'NATURAL_EXPOSURE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7469, 'Avoid ultra-processed food', 'Avoid ultra-processed food during @VARIABLE hours', 4, 'NUTRITION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7470, 'Walk in a natural environment', 'Walk in a natural environment during @VARIABLE minutes', 60, 'NATURAL_EXPOSURE', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7471, 'Prepare homemade meals', 'Prepare @VARIABLE homemade meals', 1, 'NUTRITION', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7472, 'Hold a plank', 'Hold a @VARIABLE-second plank', 40, 'EXERCISE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7473, 'Eat some vegetables', 'Eat @VARIABLE g of vegetables', 350, 'NUTRITION', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7474, 'Do several reps of a single exercise', 'Do @VARIABLE reps of a single exercise', 25, 'EXERCISE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7475, 'Avoid caffeine for the first minutes after waking', 'Avoid caffeine for @VARIABLE minutes after waking', 45, 'REGULATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7476, 'Avoid caffeine for the first minutes after waking', 'Avoid caffeine for @VARIABLE minutes after waking', 120, 'REGULATION', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7477, 'Avoid ultra-processed food', 'Avoid ultra-processed food during @VARIABLE hours', 12, 'NUTRITION', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7478, 'Do mobility work', 'Do mobility work during @VARIABLE minutes', 5, 'EXERCISE', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7479, 'Walk steps', 'Walk @VARIABLE steps', 8000, 'EXERCISE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7480, 'Walk steps', 'Walk @VARIABLE steps', 10000, 'EXERCISE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7481, 'Prepare homemade meals', 'Prepare @VARIABLE homemade meals', 5, 'NUTRITION', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7482, 'Walk in a natural environment', 'Walk in a natural environment during @VARIABLE minutes', 10, 'NATURAL_EXPOSURE', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7483, 'Sleep a reasonable amount of time', 'Sleep @VARIABLE hours', 9, 'REST', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7484, 'Avoid caffeine before sleep', 'Avoid caffeine @VARIABLE hours before sleep', 12, 'REST', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7485, 'Sleep a reasonable amount of time', 'Sleep @VARIABLE hours', 8, 'REST', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7486, 'Eat without screens', 'Eat without screens in @VARIABLE meals', 2, 'NUTRITION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7487, 'Avoid sugar', 'Avoid sugar during @VARIABLE hours', 12, 'NUTRITION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7488, 'Expose your eyes to natural light', 'Expose your eyes to natural light during @VARIABLE minutes', 10, 'NATURAL_EXPOSURE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7489, 'Avoid screens before sleep', 'Avoid screens before sleep', 50, 'RECOVERY', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7490, 'Avoid caffeine for the first minutes after waking', 'Avoid caffeine for @VARIABLE minutes after waking', 90, 'REGULATION', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7491, 'Feel gratitude without writing it', 'Feel gratitude without writing it', 2, 'GRATITUDE', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7492, 'Stand up every X minutes', 'Stand up every @VARIABLE minutes of work', 40, 'REGULATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7493, 'Go outside and walk', 'Go outside and walk during @VARIABLE minutes', 45, 'EXERCISE', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7494, 'Reflect on a positive moment', 'Reflect on a positive moment', 3, 'GRATITUDE', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7495, 'Get out of bed within some minutes after waking', 'Get out of bed within @VARIABLE minutes after waking', 8, 'REST', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7496, 'Go outside and walk', 'Go outside and walk during @VARIABLE minutes', 10, 'EXERCISE', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7497, 'Reflect on your actions today', 'Reflect on your actions today', 4, 'INTENTION', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7498, 'Eat your first meal within some hours after waking', 'Eat your first meal within @VARIABLE hours after waking', 3, 'REGULATION', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7499, 'Reflect on your actions today', 'Reflect on your actions today', 9, 'INTENTION', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7500, 'Notice something beautiful', 'Notice something beautiful', 2, 'GRATITUDE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7501, 'Write things you are grateful for', 'Write things you are grateful for', 2, 'GRATITUDE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7502, 'Stand up every X minutes', 'Stand up every @VARIABLE minutes of work', 30, 'REGULATION', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7503, 'Notice something beautiful', 'Notice something beautiful', 3, 'GRATITUDE', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7504, 'Stand up every X minutes', 'Stand up every @VARIABLE minutes of work', 50, 'REGULATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7505, 'Stop eating at…', 'Stop eating at @VARIABLE% fullness', 85, 'NUTRITION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7506, 'Write things you are grateful for', 'Write things you are grateful for', 3, 'GRATITUDE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7507, 'Reflect on what matters to you', 'Reflect on what matters to you', 10, 'INTENTION', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7508, 'Eat less than X g of sugar in a day', 'Eat less than @VARIABLE g of sugar in a day', 70, 'NUTRITION', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7509, 'Acknowledge something you have', 'Acknowledge something you have', 3, 'GRATITUDE', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7510, 'Appreciate something simple', 'Appreciate something simple', 2, 'GRATITUDE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7511, 'Eat at consistent times', 'Eat at consistent times (with a @VARIABLE minute tolerance)', 60, 'NUTRITION', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7512, 'Get out of bed within some minutes after waking', 'Get out of bed within @VARIABLE minutes after waking', 6, 'REST', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7513, 'Do a proper stretching after training', 'Do a proper @VARIABLE-minute stretching after training', 3, 'EXERCISE', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7514, 'Reflect on what matters to you', 'Reflect on what matters to you', 4, 'INTENTION', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7515, 'Eat at consistent times', 'Eat at consistent times (with a @VARIABLE minute tolerance)', 10, 'NUTRITION', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7516, 'Eat your first meal within some hours after waking', 'Eat your first meal within @VARIABLE hours after waking', 1, 'REGULATION', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7517, 'Reflect on a positive moment', 'Reflect on a positive moment', 1, 'GRATITUDE', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7518, 'Write things you are grateful for', 'Write things you are grateful for', 5, 'GRATITUDE', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7519, 'Do a proper stretching after training', 'Do a proper @VARIABLE-minute stretching after training', 20, 'EXERCISE', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7520, 'Write one meaningful goal', 'Write one meaningful goal', 2, 'INTENTION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7521, 'Protect your personal time', 'Protect your personal time', 30, 'WORK_LIFE_BALANCE', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 0),
    (7522, 'Feel gratitude without writing it', 'Feel gratitude without writing it', 4, 'GRATITUDE', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7523, 'Protect your personal time', 'Protect your personal time', 120, 'WORK_LIFE_BALANCE', 'DAILY_CHALLENGES', 1, 4, 'GAIN', 'SKILL', 3070),
    (7524, 'Write things you are grateful for', 'Write things you are grateful for', 1, 'GRATITUDE', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7525, 'Get out of bed within some minutes after waking', 'Get out of bed within @VARIABLE minutes after waking', 2, 'REST', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7526, 'Eat your first meal within some hours after waking', 'Eat your first meal within @VARIABLE hours after waking', 2, 'REGULATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7527, 'Eat less than X g of sugar in a day', 'Eat less than @VARIABLE g of sugar in a day', 40, 'NUTRITION', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7528, 'Reflect on a positive moment', 'Reflect on a positive moment', 2, 'GRATITUDE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7529, 'Do a proper stretching after training', 'Do a proper @VARIABLE-minute stretching after training', 10, 'EXERCISE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7530, 'Eat at consistent times', 'Eat at consistent times (with a @VARIABLE minute tolerance)', 45, 'NUTRITION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7531, 'Reflect on your actions today', 'Reflect on your actions today', 6, 'INTENTION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7532, 'Stop eating at…', 'Stop eating at @VARIABLE% fullness', 75, 'NUTRITION', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7533, 'Protect your personal time', 'Protect your personal time', 15, 'WORK_LIFE_BALANCE', 'DAILY_CHALLENGES', 1, 1, 'GAIN', 'SKILL', 0),
    (7534, 'Reflect on what matters to you', 'Reflect on what matters to you', 5, 'INTENTION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7535, 'Acknowledge something you have', 'Acknowledge something you have', 2, 'GRATITUDE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7536, 'Get out of bed within some minutes after waking', 'Get out of bed within @VARIABLE minutes after waking', 10, 'REST', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7537, 'Eat less than X g of sugar in a day', 'Eat less than @VARIABLE g of sugar in a day', 60, 'NUTRITION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7538, 'Reflect on your actions today', 'Reflect on your actions today', 3, 'INTENTION', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7539, 'Appreciate something simple', 'Appreciate something simple', 3, 'GRATITUDE', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7540, 'Protect your personal time', 'Protect your personal time', 60, 'WORK_LIFE_BALANCE', 'DAILY_CHALLENGES', 1, 3, 'GAIN', 'SKILL', 0),
    (7541, 'Eat at consistent times', 'Eat at consistent times (with a @VARIABLE minute tolerance)', 30, 'NUTRITION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7542, 'Reflect on your actions today', 'Reflect on your actions today', 7, 'INTENTION', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7543, 'Go outside and walk', 'Go outside and walk during @VARIABLE minutes', 60, 'EXERCISE', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7544, 'Appreciate something simple', 'Appreciate something simple', 1, 'GRATITUDE', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7545, 'Stand up every X minutes', 'Stand up every @VARIABLE minutes of work', 20, 'REGULATION', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7546, 'Write one meaningful goal', 'Write one meaningful goal', 1, 'INTENTION', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7547, 'Feel gratitude without writing it', 'Feel gratitude without writing it', 5, 'GRATITUDE', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7548, 'Stop eating at…', 'Stop eating at @VARIABLE% fullness', 90, 'NUTRITION', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7549, 'Eat at consistent times', 'Eat at consistent times (with a @VARIABLE minute tolerance)', 20, 'NUTRITION', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7550, 'Reflect on what matters to you', 'Reflect on what matters to you', 3, 'INTENTION', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7551, 'Do a proper stretching after training', 'Do a proper @VARIABLE-minute stretching after training', 5, 'EXERCISE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7552, 'Reflect on your actions today', 'Reflect on your actions today', 8, 'INTENTION', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7553, 'Eat less than X g of sugar in a day', 'Eat less than @VARIABLE g of sugar in a day', 25, 'NUTRITION', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7554, 'Reflect on what matters to you', 'Reflect on what matters to you', 8, 'INTENTION', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7555, 'Eat less than X g of sugar in a day', 'Eat less than @VARIABLE g of sugar in a day', 50, 'NUTRITION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7556, 'Reflect on what matters to you', 'Reflect on what matters to you', 7, 'INTENTION', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7557, 'Get out of bed within some minutes after waking', 'Get out of bed within @VARIABLE minutes after waking', 4, 'REST', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7558, 'Stop eating at…', 'Stop eating at @VARIABLE% fullness', 80, 'NUTRITION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7559, 'Reflect on your actions today', 'Reflect on your actions today', 5, 'INTENTION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7560, 'Go outside and walk', 'Go outside and walk during @VARIABLE minutes', 20, 'EXERCISE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7561, 'Go outside and walk', 'Go outside and walk during @VARIABLE minutes', 30, 'EXERCISE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7562, 'Write things you are grateful for', 'Write things you are grateful for', 4, 'GRATITUDE', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7563, 'Reflect on your actions today', 'Reflect on your actions today', 10, 'INTENTION', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7564, 'Do a proper stretching after training', 'Do a proper @VARIABLE-minute stretching after training', 15, 'EXERCISE', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7565, 'Stand up every X minutes', 'Stand up every @VARIABLE minutes of work', 60, 'REGULATION', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7566, 'Notice something beautiful', 'Notice something beautiful', 1, 'GRATITUDE', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7567, 'Acknowledge something you have', 'Acknowledge something you have', 1, 'GRATITUDE', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7568, 'Feel gratitude without writing it', 'Feel gratitude without writing it', 3, 'GRATITUDE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7569, 'Reflect on what matters to you', 'Reflect on what matters to you', 9, 'INTENTION', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7570, 'Stop eating at…', 'Stop eating at @VARIABLE% fullness', 70, 'NUTRITION', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7571, 'Write one meaningful goal', 'Write one meaningful goal', 3, 'INTENTION', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7572, 'Reflect on what matters to you', 'Reflect on what matters to you', 6, 'INTENTION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7573, 'Take a walk without your phone', 'Take a @VARIABLE-minute walk without your phone', 30, 'RECOVERY', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 0),
    (7574, 'Work with no background audio', 'Work with no background audio during @VARIABLE minutes', 20, 'FOCUS', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7575, 'Set a random timer to take breaks through your day', 'Set a random timer to take breaks through your day', 6, 'CLARITY', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7576, 'Pause and ask “why am I doing this?”', 'Pause and ask “why am I doing this?”', 3, 'INTENTION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7577, 'Use grayscale mode', 'Use grayscale mode during @VARIABLE hours', 2, 'TECH_BALANCE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7578, 'Choose one intentional action', 'Choose one intentional action', 1, 'INTENTION', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7579, 'Leave your phone out of your visual sight', 'Leave your phone out of your visual sight during @VARIABLE minutes', 20, 'FOCUS', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7580, 'Leave your phone out of your visual sight', 'Leave your phone out of your visual sight during @VARIABLE minutes', 60, 'FOCUS', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7581, 'Really feel the ground under your feet when you walk', 'Really feel the ground under your feet when you walk during @VARIABLE minutes', 4, 'MEDITATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7582, 'Use grayscale mode', 'Use grayscale mode during @VARIABLE hours', 12, 'TECH_BALANCE', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7583, 'Take a walk without your phone', 'Take a @VARIABLE-minute walk without your phone', 10, 'RECOVERY', 'DAILY_CHALLENGES', 1, 1, 'GAIN', 'SKILL', 0),
    (7584, 'Leave your phone out of your visual sight', 'Leave your phone out of your visual sight during @VARIABLE minutes', 30, 'FOCUS', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7585, 'Work with no background audio', 'Work with no background audio during @VARIABLE minutes', 45, 'FOCUS', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7586, 'Leave your phone out of your visual sight', 'Leave your phone out of your visual sight during @VARIABLE minutes', 45, 'FOCUS', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7587, 'Act in alignment with your values', 'Act in alignment with your values', 2, 'INTENTION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7588, 'Pause and ask “why am I doing this?”', 'Pause and ask “why am I doing this?”', 5, 'INTENTION', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7589, 'Say “thank you” with intention', 'Say “thank you” with intention', 4, 'GRATITUDE', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7590, 'Really feel the ground under your feet when you walk', 'Really feel the ground under your feet when you walk during @VARIABLE minutes', 10, 'MEDITATION', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7591, 'Take a walk without your phone', 'Take a @VARIABLE-minute walk without your phone', 20, 'RECOVERY', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 0),
    (7592, 'Say “thank you” with intention', 'Say “thank you” with intention', 2, 'GRATITUDE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7593, 'Set a random timer to take breaks through your day', 'Set a random timer to take breaks through your day', 4, 'CLARITY', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7594, 'Pause and ask “why am I doing this?”', 'Pause and ask “why am I doing this?”', 2, 'INTENTION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7595, 'Choose one intentional action', 'Choose one intentional action', 3, 'INTENTION', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7596, 'Pause and take slow breaths', 'Pause and take slow breaths', 7, 'CLARITY', 'DAILY_CHALLENGES', 1, 4, 'GAIN', 'SKILL', 4050),
    (7597, 'Pause and ask “why am I doing this?”', 'Pause and ask “why am I doing this?”', 4, 'INTENTION', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7598, 'Take a walk without your phone', 'Take a @VARIABLE-minute walk without your phone', 50, 'RECOVERY', 'DAILY_CHALLENGES', 1, 4, 'GAIN', 'SKILL', 2050),
    (7599, 'Pause and take slow breaths', 'Pause and take slow breaths', 6, 'CLARITY', 'DAILY_CHALLENGES', 1, 3, 'GAIN', 'SKILL', 0),
    (7600, 'Set a random timer to take breaks through your day', 'Set a random timer to take breaks through your day', 2, 'CLARITY', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7601, 'Set a random timer to take breaks through your day', 'Set a random timer to take breaks through your day', 10, 'CLARITY', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7602, 'Act in alignment with your values', 'Act in alignment with your values', 1, 'INTENTION', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7603, 'Pause and take slow breaths', 'Pause and take slow breaths', 4, 'CLARITY', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 0),
    (7604, 'Really feel the ground under your feet when you walk', 'Really feel the ground under your feet when you walk during @VARIABLE minutes', 8, 'MEDITATION', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7605, 'Use grayscale mode', 'Use grayscale mode during @VARIABLE hours', 1, 'TECH_BALANCE', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7606, 'Set a random timer to take breaks through your day', 'Set a random timer to take breaks through your day', 8, 'CLARITY', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7607, 'Say “thank you” with intention', 'Say “thank you” with intention', 1, 'GRATITUDE', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7608, 'Work with no background audio', 'Work with no background audio during @VARIABLE minutes', 10, 'FOCUS', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7609, 'Take a walk without your phone', 'Take a @VARIABLE-minute walk without your phone', 40, 'RECOVERY', 'DAILY_CHALLENGES', 1, 3, 'GAIN', 'SKILL', 0),
    (7610, 'Work with no background audio', 'Work with no background audio during @VARIABLE minutes', 60, 'FOCUS', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7611, 'Really feel the ground under your feet when you walk', 'Really feel the ground under your feet when you walk during @VARIABLE minutes', 6, 'MEDITATION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7612, 'Choose one intentional action', 'Choose one intentional action', 2, 'INTENTION', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7613, 'Pause and ask “why am I doing this?”', 'Pause and ask “why am I doing this?”', 1, 'INTENTION', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7614, 'Use grayscale mode', 'Use grayscale mode during @VARIABLE hours', 8, 'TECH_BALANCE', 'DAILY_CHALLENGES', 1, 3, NULL, '', 0),
    (7615, 'Pause and take slow breaths', 'Pause and take slow breaths', 5, 'CLARITY', 'DAILY_CHALLENGES', 1, 2, 'GAIN', 'SKILL', 0),
    (7616, 'Act in alignment with your values', 'Act in alignment with your values', 3, 'INTENTION', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7617, 'Really feel the ground under your feet when you walk', 'Really feel the ground under your feet when you walk during @VARIABLE minutes', 2, 'MEDITATION', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7618, 'Use grayscale mode', 'Use grayscale mode during @VARIABLE hours', 4, 'TECH_BALANCE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7619, 'Leave your phone out of your visual sight', 'Leave your phone out of your visual sight during @VARIABLE minutes', 10, 'FOCUS', 'DAILY_CHALLENGES', 1, 1, NULL, '', 0),
    (7620, 'Say “thank you” with intention', 'Say “thank you” with intention', 5, 'GRATITUDE', 'DAILY_CHALLENGES', 1, 4, NULL, '', 0),
    (7621, 'Pause and take slow breaths', 'Pause and take slow breaths', 3, 'CLARITY', 'DAILY_CHALLENGES', 1, 1, 'GAIN', 'SKILL', 0),
    (7622, 'Work with no background audio', 'Work with no background audio during @VARIABLE minutes', 30, 'FOCUS', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0),
    (7623, 'Say “thank you” with intention', 'Say “thank you” with intention', 3, 'GRATITUDE', 'DAILY_CHALLENGES', 1, 2, NULL, '', 0);