name: Mobile CI/CD (Dev)

on:
  push:
    branches:
      - develop
      - bugfix/android_tests_on_cicd
    paths:
      - 'mobile/**'
      - '.github/workflows/dev-mobile-workflow.yml'

jobs:
  mobile-ci:
    name: Test and Build APK
    runs-on: ubuntu-latest

    environment:
      name: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant Gradle permissions
        run: chmod +x ./gradlew
        working-directory: ./mobile

      - name: Set API URL
        run: echo "MOBILE_API_URL=${{ secrets.MOBILE_API_URL }}" >> $GITHUB_ENV

      - name: Set COMPANY EMAIL
        run: echo "MOBILE_COMPANY_EMAIL=${{ secrets.MOBILE_COMPANY_EMAIL }}" >> $GITHUB_ENV

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
        
      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Configure Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            # Ensure the emulator is started correctly
            echo "Configuring the emulator."

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck

      - name: Run unit tests
        run: ./gradlew test
        working-directory: ./mobile

      - name: Build debug APK with CI versioning
        run: |
          ./gradlew assembleDebug -PversionCode=${{ github.run_number }} -PversionName="0.0.${{ github.sha }}"
        working-directory: ./mobile

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: kiwi-project-debug-apk-${{ github.run_number }}
          path: mobile/app/build/outputs/apk/debug/app-debug.apk

      - name: Write service account key
        run: echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' > ${GITHUB_WORKSPACE}/firebase-key.json

      - name: Upload APK to Firebase App Distribution
        uses: w9jds/firebase-action@v14.1.0
        with:
          args: appdistribution:distribute mobile/app/build/outputs/apk/debug/app-debug.apk --app ${{ secrets.FIREBASE_APP_ID }} --project ${{ secrets.FIREBASE_PROJECT_ID }} --groups "dev-testers" --debug
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-key.json