name: Backend CI/CD (Dev)
  
on:
  push:
    branches:
      - develop
      - feature/ci-cd
    paths:
      - 'backend/**'
      - '.github/workflows/dev-backend-workflow.yml'
      - 'k8s/dev/dev-backend-deployment.yaml'
      - 'k8s/dev/dev-backend-service.yaml'
  pull_request:
    branches:
      - develop
      - feature/ci-cd
    paths:
      - 'backend/**'
      - '.github/workflows/dev-backend-workflow.yml'
      - 'k8s/dev/dev-backend-deployment.yaml'
      - 'k8s/dev/dev-backend-service.yaml'

jobs:
  backend-ci-cd:
    name: Test, Build, and Push Backend
    runs-on: ubuntu-latest

    environment:
      name: dev

    env:
      BACKEND_DB_URL: ${{ secrets.BACKEND_DB_URL }}
      BACKEND_DB_USERNAME: ${{ secrets.BACKEND_DB_USERNAME }}
      BACKEND_DB_PASSWORD: ${{ secrets.BACKEND_DB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Run backend tests
        working-directory: ./backend
        run: |
          chmod +x mvnw
          ./mvnw test

      - name: Build and push Docker image
        working-directory: ./backend
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/kiwi-project
          GIT_SHA=${{ github.sha }}

          docker build -t $IMAGE_NAME:backend-dev-$GIT_SHA -t $IMAGE_NAME:backend-dev:latest -f Dockerfile.dev .

          docker push $IMAGE_NAME:backend-dev-$GIT_SHA
          docker push $IMAGE_NAME:backend-dev:latest
      
      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Create Kubernetes secrets for backend
        run: |
          kubectl create secret generic backend-secret \
            --from-literal=BACKEND_DB_URL_K8S=${{ secrets.BACKEND_DB_URL_K8S }} \
            --from-literal=BACKEND_DB_USERNAME=${{ secrets.BACKEND_DB_USERNAME }} \
            --from-literal=BACKEND_DB_PASSWORD=${{ secrets.BACKEND_DB_PASSWORD }} \
            --namespace=dev \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Create DockerHub Secret for Private Image Pulling
        run: |
          kubectl create secret docker-registry dockerhub-secret \
            --docker-server=https://index.docker.io/v1/ \
            --docker-username=${{ secrets.DOCKERHUB_USERNAME }} \
            --docker-password=${{ secrets.DOCKERHUB_TOKEN }} \
            --docker-email=${{ secrets.DOCKERHUB_EMAIL }} \
            --namespace=dev \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Set up (or update) kubernetes accounts, roles, and bindings
        run: |
          kubectl apply -f k8s/dev/dev-service-account.yaml --overwrite
          kubectl apply -f k8s/dev/dev-cluster-role.yaml --overwrite
          kubectl apply -f k8s/dev/dev-cluster-role-binding.yaml --overwrite

      - name: Get Fresh Kubernetes Service Account Token 
        run: |
          export TOKEN=$(kubectl -n dev create token kiwi-ci-cd-service-account --duration=600s)
          echo "K8S_TOKEN=${TOKEN}" >> $GITHUB_ENV
        

      - name: Deploy to Kubernetes (dev)
        uses: appleboy/kubernetes-action@v0.0.1
        with:
          server: ${{ secrets.K8S_SERVER }}
          ca_cert: ${{ secrets.K8S_CA_CERT }}
          token: ${{ env.K8S_TOKEN }}
          namespace: dev
          templates: k8s/dev/dev-backend-*.yaml