name: Mobile CI/CD (Prod)

on:
  push:
    branches:
      - main
      - feature/ci-cd
    tags:
      - 'v*'
    paths:
      - 'mobile/**'
      - '.github/workflows/prod-mobile-workflow.yml'
  pull_request:
    branches:
      - main
      - feature/ci-cd
    tags:
        - 'v*'
    paths:
      - 'mobile/**'
      - '.github/workflows/prod-mobile-workflow.yml'

jobs:
  mobile-ci:
    name: Test and Build APK
    runs-on: ubuntu-latest

    environment:
      name: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Write .env file
        run: |
          echo "${{ secrets.MOBILE_API_URL }}" > mobile/.env.prod

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant Gradle permissions
        run: chmod +x ./gradlew
        working-directory: ./mobile

      - name: Run unit tests
        run: ./gradlew test
        working-directory: ./mobile

      - name: Build Release APK with CI versioning
        run: |
          ./gradlew assembleRelease -PversionCode=${{ github.run_number }} -PversionName="0.1.${{ github.sha }}"
        working-directory: ./mobile

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: kiwi-project-release-apk-${{ github.run_number }}
          path: mobile/app/build/outputs/apk/release/app-release.apk
          
      - name: Set APK Version 
        run: |
          VERSION_TAG=$(git describe --tags --abbrev=0 || date +'%Y-%m-%d-%H%M%S')
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
      
      # - name: Upload to Google Play Internal Test Track
      #   uses: r0adkll/upload-google-play@v1
      #   with:
      #     serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
      #     packageName: com.kiwi
      #     releaseFile: mobile/app/build/outputs/apk/release/app-release.apk
      #     track: internal
      #     status: completed

