name: Mobile CI/CD (Prod)

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - 'mobile/**'
      - '.github/workflows/prod-mobile-workflow.yml'
  pull_request:
    branches:
      - main
    tags:
        - 'v*'
    paths:
      - 'mobile/**'
      - '.github/workflows/prod-mobile-workflow.yml'

jobs:
  mobile-ci:
    name: Test and Build APK
    runs-on: ubuntu-latest

    environment:
      name: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Write .env file
        run: |
          echo "${{ secrets.MOBILE_API_URL }}" > mobile/.env.prod

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant Gradle permissions
        run: chmod +x ./gradlew
        working-directory: ./mobile

      - name: Setup Gradle Cache
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Run tests
        run: ./gradlew test
        working-directory: ./mobile

      - name: Generate version tag, push it, and export version info
        id: version
        run: |
          VERSION_BASE="v0.0."
          LATEST_TAG=$(git tag --sort=-v:refname | grep '^v0.0.' | tail -n 1)
          LAST_PATCH=$(echo $LATEST_TAG | cut -d'.' -f3)
          NEXT_PATCH=$((LAST_PATCH + 1))
          NEW_TAG="${VERSION_BASE}${NEXT_PATCH}"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag $NEW_TAG
          git push origin $NEW_TAG

          TAG=${NEW_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$TAG"
          VERSION_CODE=$((MAJOR * 1000000 + MINOR * 1000 + PATCH))
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          echo "VERSION_NAME=$TAG" >> $GITHUB_ENV

      - name: Build AAb
        run: ./gradlew bundleRelease -PversionCode=$VERSION_CODE -PversionName=$VERSION_NAME
        working-directory: ./mobile

      - name: Sign AAb
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: mobile/app/build/outputs/bundle/release
          signingKeyBase64: '${{ secrets.KEYSTORE }}'
          alias: '${{ secrets.SIGNING_KEY_ALIAS }}'
          keyStorePassword: '${{ secrets.SIGNING_STORE_PASSWORD }}'
          keyPassword: '${{ secrets.SIGNING_KEY_PASSWORD }}'

      - name: Upload app bundle as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: mobile/app/build/outputs/bundle/release/app-release.aab

      - name: Download app bundle from artifact
        uses: actions/download-artifact@v4.2.1
        with:
          name: app-bundle

      - name: Upload to Google Play Internal Test Track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: '${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}'
          packageName: com.bellako.kiwi
          releaseFiles: 'mobile/app/build/outputs/bundle/release/app-release.aab'
          track: internal